export const styles = {
  authContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  authCard: {
    backgroundColor: '#1f2937',
    padding: '2rem',
    borderRadius: '1rem',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.3)',
    width: '100%',
    maxWidth: '400px',
  },
  authTitle: {
    fontSize: '1.875rem',
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: '1.5rem',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  input: {
    padding: '0.75rem',
    borderRadius: '0.5rem',
    border: '1px solid #374151',
    backgroundColor: '#111827',
    color: '#ffffff',
    fontSize: '1rem',
  },
  button: {
    padding: '0.75rem',
    borderRadius: '0.5rem',
    border: 'none',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  genderContainer: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'center',
  },
  genderLabel: {
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  switchText: {
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: '1rem',
  },
  link: {
    color: '#3b82f6',
    cursor: 'pointer',
    textDecoration: 'underline',
  },
  homeContainer: {
    display: 'flex',
    height: '100vh',
    backgroundColor: '#111827',
  },
  sidebar: {
    width: '300px',
    backgroundColor: '#1f2937',
    borderRight: '1px solid #374151',
    display: 'flex',
    flexDirection: 'column',
  },
  sidebarHeader: {
    padding: '1rem',
    borderBottom: '1px solid #374151',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sidebarTitle: {
    color: '#ffffff',
    fontSize: '1.25rem',
    fontWeight: 'bold',
  },
  logoutButton: {
    padding: '0.5rem 1rem',
    borderRadius: '0.5rem',
    border: 'none',
    backgroundColor: '#ef4444',
    color: '#ffffff',
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  conversationsList: {
    flex: 1,
    overflowY: 'auto',
  },
  conversation: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.75rem 1rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    gap: '0.75rem',
  },
  avatarContainer: {
    position: 'relative',
  },
  avatar: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
  },
  onlineBadge: {
    position: 'absolute',
    bottom: '2px',
    right: '2px',
    width: '12px',
    height: '12px',
    backgroundColor: '#10b981',
    borderRadius: '50%',
    border: '2px solid #1f2937',
  },
  conversationInfo: {
    flex: 1,
  },
  conversationName: {
    color: '#ffffff',
    fontWeight: '500',
    margin: 0,
  },
  messageContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  messageHeader: {
    padding: '1rem',
    backgroundColor: '#1f2937',
    borderBottom: '1px solid #374151',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  headerAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
  },
  headerName: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: '1.125rem',
  },
  messagesArea: {
    flex: 1,
    overflowY: 'auto',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  messageWrapper: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'flex-end',
  },
  messageAvatar: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
  },
  messageBubble: {
    maxWidth: '70%',
    padding: '0.75rem',
    borderRadius: '1rem',
  },
  messageText: {
    color: '#ffffff',
    margin: 0,
    marginBottom: '0.25rem',
    wordBreak: 'break-word',
  },
  messageTime: {
    color: '#d1d5db',
    fontSize: '0.75rem',
  },
  messageForm: {
    padding: '1rem',
    backgroundColor: '#1f2937',
    borderTop: '1px solid #374151',
    display: 'flex',
    gap: '0.75rem',
  },
  messageInput: {
    flex: 1,
    padding: '0.75rem',
    borderRadius: '0.5rem',
    border: '1px solid #374151',
    backgroundColor: '#111827',
    color: '#ffffff',
    fontSize: '1rem',
  },
  sendButton: {
    padding: '0.75rem 1.5rem',
    borderRadius: '0.5rem',
    border: 'none',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
  },
  noChat: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#9ca3af',
  },
  noChatTitle: {
    fontSize: '2rem',
    marginBottom: '1rem',
  },
  noChatText: {
    fontSize: '1.125rem',
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '2rem',
    color: '#9ca3af',
  },
};